version: '2'
services:
  go:
    image: go-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    #network_mode: "host"
    container_name: go_app
    ports: 
       - "8080:8080"
#    volumes:
#      - ./STORAGE:/app/STORAGE


